run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - errcheck
        - unused
    # Exclude SA5011 (possible nil pointer dereference) false positives
    # These occur when we check `if x == nil` and return early,
    # but staticcheck doesn't recognize the early return pattern
    - linters:
        - staticcheck
      text: "SA5011"

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

output:
  sort-results: true
